# Generated by Django 4.0.3 on 2022-05-15 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('kdp_wb', '0005_answer_voter_question_voter_alter_answer_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'permissions': [('can_publish', 'Can Publish Posts'), ('can_change', 'Can Change Posts'), ('can_view', 'Can View Posts'), ('can_delete', 'Can Delete Posts')]},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': [('can_publish', 'Can Publish Posts'), ('can_change', 'Can Change Posts'), ('can_view', 'Can View Posts'), ('can_delete', 'Can Delete Posts')]},
        ),
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
