# Generated by Django 4.0.3 on 2022-06-08 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kdp_wb', '0007_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_clientanswer', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kdp_wb.client')),
            ],
            options={
                'permissions': [('can_publish', 'Can Publish Posts'), ('can_change', 'Can Change Posts'), ('can_view', 'Can View Posts'), ('can_delete', 'Can Delete Posts')],
            },
        ),
    ]
