# Generated by Django 4.0.3 on 2022-06-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdp_wb', '0008_clientanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='agree',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
