# Generated by Django 4.0.3 on 2022-06-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdp_wb', '0009_client_agree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='agree',
            field=models.CharField(max_length=1),
        ),
    ]
